### ISSUE TITLE
你的机器人会自动发图片 是不是bug啊

### ISSUE THREAD

**Issue by chinajtsn** [silvicky/VickyBot#1]
https://www.sohu.com/a/493964413_121123829

![photo_2024-01-14_14-04-52](https://github.com/silvicky/VickyBot/assets/157932327/a5328d38-ce88-42c4-a4f5-ce580175841a)
![photo_2024-01-14_14-04-54](https://github.com/silvicky/VickyBot/assets/157932327/e3cd239b-d71c-4806-9f2a-2e4d353d2426)
![photo_2024-01-27_01-23-31](https://github.com/silvicky/VickyBot/assets/157932327/5450689b-cc6e-4968-8368-8dbb1e1a1ccb)

**Comment by silvicky** [comment]
handsome very handsome
